apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: USERNAME
          value: pablo
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
